name: Build and deploy demo

on: 
  push:
    branches: "main"
 
jobs: 
  build-and-deploy:
    name: "Build and deploy"
    env:
      workspace_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      qt_version: '6.8.1'
      qt_host_arch: 'gcc_64'
      qt_target_arch: 'wasm_singlethread'
      qt_modules: 'wasm_singlethread qtquick3d'
      qt_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/Qt'
      qt_root_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      target_folder: 'QtQuick3D-Tools'
      source_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/build/example'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'true'
 
      - name: Install tools
        shell: bash
        run: |
          sudo apt-get -y install jq lftp brotli expect

      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Debug
        shell: bash
        continue-on-error: true
        run: |
          ls -la '/home/runner/.local/share/Qt/' || 0
          cat '/home/runner/.local/share/Qt/qtaccount.ini' || 0
          ls -la '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/' || 0
          ls -la '/home/runner/.local/share/aqt/tmp/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64/6.8.1' || 0
          cat '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64/6.8.1/packages.json' || 0
          mkdir -p '/home/runner/.local/share' || 0
          chmod 777 '/home/runner/.local/share' || 0

      - name: Install Qt
        uses: Kidev/install-qt-action@v4.4.3
        continue-on-error: true
        with:
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@fix_official_tty'
          version: '6.8.1'
          target: 'desktop'
          arch: 'linux_gcc_64'
          use-official: true
          email: ${{ secrets.QT_USERNAME }}
          pw: ${{ secrets.QT_PASSWORD }}
          modules: ${{ env.qt_modules }}
          dir: ${{ env.qt_root_folder }}

      - name: Debug
        shell: bash
        continue-on-error: true
        run: |
          ls -la '/home/runner/.local/share/Qt/' || 0
          cat '/home/runner/.local/share/Qt/qtaccount.ini' || 0
          ls -la '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/' || 0
          ls -la '/home/runner/.local/share/aqt/tmp/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64' || 0
          ls -la '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64/6.8.1' || 0
          cat '/home/runner/.local/share/aqt/cache/desktop/linux_gcc_64/6.8.1/packages.json' || 0
    
      - name: CMake Build
        shell: bash
        run: |
          make web \
            QT_ROOT=${{ env.qt_root }} \
            QT_VERSION=${{ env.qt_version }} \
            QT_HOST_ARCH=${{ env.qt_host_arch }} \
            QT_TARGET_ARCH=${{ env.qt_target_arch }}

      - name: Upload to FTP
        shell: bash
        run: |
          lftp -u "${{ secrets.FTP_UPLOAD_USER }}","${{ secrets.FTP_UPLOAD_PW }}" ${{ secrets.FTP_UPLOAD_IP }} <<EOF
          set ssl:verify-certificate no
          mirror -R --only-newer --verbose ${{ env.source_folder }} ${{ env.target_folder }}
          quit
          EOF
