name: Build and deploy demo

on: 
  push:
    branches: "main"

jobs:
  build-and-deploy:
    name: "Build and deploy"
    env:
      workspace_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      qt_version: '6.8.1'
      qt_host_arch: 'gcc_64'
      qt_target_arch: 'wasm_singlethread'
      qt_modules: 'qtquick3d qtshadertools wasm_singlethread'
      qt_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/Qt'
      target_folder: 'QtQuick3D-Tools'
      source_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/build/example'
      DISPLAY: ':99.0'
      XDG_RUNTIME_DIR: '/tmp/runtime-runner'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'true'
 
      - name: Install tools
        shell: bash
        run: |
          sudo apt-get -y install jq lftp brotli expect xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          sleep 3
          sudo mkdir -p /home/runner/.local/share/aqt
          sudo mkdir -p /home/runner/.local/share/Qt
          sudo chown -R runner:runner /home/runner/.local/share/aqt
          sudo chown -R runner:runner /home/runner/.local/share/Qt
          sudo chmod -R 755 /home/runner/.local/share/aqt
          sudo chmod -R 755 /home/runner/.local/share/Qt
          mkdir -p $XDG_RUNTIME_DIR
          chmod 700 $XDG_RUNTIME_DIR

      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Qt
        uses: Kidev/install-qt-action@v4.4.2
        with:
          version: '6.8.1'
          target: 'desktop'
          arch: 'linux_gcc_64'
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@install_qt_commercial'
          use-commercial: true
          user: ${{ secrets.QT_USERNAME }}
          password: ${{ secrets.QT_PASSWORD }}
          modules: ${{ env.qt_modules }}
          dir: ${{ env.qt_root }}

      - name: Verify Qt Installation
        shell: bash
        run: |
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch }}/lib
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_arch }}/lib
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch }}/lib/cmake
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_arch }}/lib/cmake
          
      - name: CMake Build
        shell: bash
        run: |
          make web \
            QT_ROOT=${{ env.qt_root }} \
            QT_VERSION=${{ env.qt_version }} \
            QT_HOST_ARCH=${{ env.qt_host_arch }} \
            QT_TARGET_ARCH=${{ env.qt_target_arch }}

      - name: Upload to FTP
        shell: bash
        run: |
          lftp -u "${{ secrets.FTP_UPLOAD_USER }}","${{ secrets.FTP_UPLOAD_PW }}" ${{ secrets.FTP_UPLOAD_IP }} <<EOF
          set ssl:verify-certificate no
          mirror -R --only-newer --verbose ${{ env.source_folder }} ${{ env.target_folder }}
          quit
          EOF
