name: Build tests

on: 
  push:
    branches: "main"
 
jobs: 
  build-and-deploy:
    name: "Build tests"
    runs-on: ubuntu-24.04
    steps:
      - name: Install Qt 
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          tools: 'tools_ifw'
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@fix_ifw'
