name: Build tests

on: 
  push:
    branches: "main"
 
jobs: 
  build-and-deploy:
    name: "Build tests"
    runs-on: ubuntu-24.04
    steps:
      - name: Install Qt 
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          aqtversion: '3.2.*'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtcharts qtvirtualkeyboard'
          extra: '-b https://mirrors.dotsrc.org/qtproject'
