name: Build tests

on: 
  push:
    branches: "main"
 
jobs: 
  build-and-deploy:
    name: "Build tests"
    runs-on: windows-11-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'true'
 
      - name: Install Qt 
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_arm64_cross_compiled'
          modules: 'qtshadertools qtimageformats'
          use-official: true
          email: ${{ secrets.QT_USERNAME2 }}
          pw: ${{ secrets.QT_PASSWORD2 }}
  
      - name: CMake Build
        shell: bash
        run: make desktop
